name: zrok TCP Tunnel Proxy Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: System info
        run: |
          uname -a
          echo "Public IP:"
          curl -4 api.ipify.org
          echo


      - name: Install 3proxy
        run: |
          sudo apt update
          sudo apt install -y git build-essential curl wget jq

          git clone https://github.com/z3APA3A/3proxy.git

          cd 3proxy
          make -f Makefile.Linux

          sudo cp bin/3proxy /usr/local/bin/3proxy


      - name: Start 3proxy
        run: |
          printf '%s\n' \
          "daemon" \
          "nscache 65536" \
          "nserver 8.8.8.8" \
          "nserver 1.1.1.1" \
          "auth none" \
          "proxy -p9000" \
          > 3proxy.cfg

          nohup 3proxy 3proxy.cfg > 3proxy.log 2>&1 &

          sleep 5

          echo "========== 3PROXY LOG =========="
          cat 3proxy.log || true

          echo "========== PORT CHECK =========="
          ss -lntp | grep 9000 || true

          echo "========== LOCAL TEST =========="
          curl -x http://127.0.0.1:9000 http://example.com -v || true


      - name: Install zrok
        run: |
          sudo apt update
          sudo apt install -y jq curl wget

          URL=$(curl -s https://api.github.com/repos/openziti/zrok/releases/latest \
          | jq -r '.assets[].browser_download_url' \
          | grep linux \
          | grep amd64 \
          | head -n1)

          echo "Downloading:"
          echo "$URL"

          wget "$URL" -O zrok.tar.gz

          echo "========== TAR =========="
          tar -tzf zrok.tar.gz

          tar -xzf zrok.tar.gz

          echo "========== FILES =========="
          ls -la

          sudo install ./zrok2 /usr/local/bin/zrok

          sudo chmod +x /usr/local/bin/zrok

          zrok version || true


      - name: Enable zrok
        env:
          ZROK_TOKEN: V0OUklFRSSiy
        run: |
          echo "$ZROK_TOKEN" | zrok enable -


      - name: Start zrok TCP tunnel
        run: |
          echo "Starting zrok TCP tunnel..."

          nohup zrok share private \
          --backend-mode tcpTunnel \
          localhost:9000 \
          > zrok.log 2>&1 &

          sleep 20

          echo "========== ZROK LOG =========="
          cat zrok.log || true


      - name: Keep alive
        run: |
          echo "Proxy tunnel is running..."

          while true
          do
            sleep 60
          done
